---
- name: Host Reboot | Include variables
  ansible.builtin.include_tasks: variables.yml
  args:
    apply:
      tags: linux-os-reboot
  tags: linux-os-reboot
  when: update_satellite_facts

- name: "Host Reboot | Include Tasks for Host Reboot (RedHat)"
  ansible.builtin.include_tasks: reboot-rhel.yml
  args:
    apply:
      tags:
        - linux-os-reboot
        - rhel-os-reboot
      become: yes
  tags:
    - linux-os-reboot
    - rhel-os-reboot
  when: ansible_os_family == 'RedHat'
...
