---
- name: Host Reboot | Install yum-utils (rhel7)
  ansible.builtin.yum:
    name:
      - katello-host-tools
      - yum-utils
    enablerepo:
      - "rhel-7-server-satellite-tools-{{ satellite_version }}-rpms"
    state: present
  when:
    - ansible_distribution_major_version is version('7', '==')
    - satellite_version is defined
    - update_satellite_facts

- block:
  - name: Host Reboot | Detect if reboot is required (rhel7)
    ansible.builtin.command:
      cmd: needs-restarting --reboothint
    register: needs_restart_result_rh7
    failed_when: needs_restart_result_rh7.rc > 1
    changed_when: needs_restart_result_rh7.rc == 1
    when: ansible_distribution_major_version is version('7', '==')
  when: reboot_only_if_needed

- name: Host Reboot | Schedule Reboot (rhel7)
  ansible.builtin.reboot:
    pre_reboot_delay: 10
    post_reboot_delay: 65
    reboot_timeout: 1800
    test_command: uptime
  when:
    - needs_restart_result_rh7 is changed or not reboot_only_if_needed
    - ansible_distribution_major_version is version('7', '==')

- name: "Host Reboot | Update Satellite facts (rhel7)"
  ansible.builtin.shell: "{{ item }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/sbin"
  loop:
    - "subscription-manager facts --update"
    - "katello-package-upload"
  when:
     - ansible_distribution_major_version is version('7', '==')
     - satellite_version is defined
     - update_satellite_facts
...
