---
# defaults file for linux_os_reboot

#  Reboot only when needed
reboot_only_if_needed: true

# Should update satellite facts?
update_satellite_facts: false

# Satellite Version
satellite_version: 6.9
...
