---
- name: Include Prerequisites Tasks to check before upgrade
  include_tasks: prerequisites.yml
  args:
    apply:
      tags: prerequisites
  tags: prerequisites

- name: Update OS | Include variables
  ansible.builtin.include_tasks: variables.yml
  args:
    apply:
      tags: always
  tags: always

- name: "Update OS | Include tasks for the corresponding release major version"
  include_tasks: "os-update-rhel.yml"
  args:
    apply:
      tags:
        - os-update-rhel
      become: yes
  tags:
    - os-update-rhel
...
