---
- name: "Update OS | Any package updates required?"
  ansible.builtin.command:
    cmd: 'yum check-update'
  args:
    warn: no
  register: packages_need_update_result_rhel
  changed_when: packages_need_update_result_rhel.rc == 100
  failed_when: packages_need_update_result_rhel.rc != 0 and packages_need_update_result_rhel.rc != 100

- name: "Update OS | Update All Packages"
  ansible.builtin.yum:
    name: '*'
    state: latest
    disablerepo: "{{ disable_repository_list }}"
    enablerepo: "{{ enable_repository_list }}"
    exclude: "{{ exclude_packages_list }}"
  async: 1000
  poll: 0
  register: yum_sleeper_rhel
  when:
    - yum_update
    - packages_need_update_result_rhel is changed

- name: "YUM - check on async task yum_sleeper_rhel"
  ansible.builtin.async_status:
    jid: "{{ yum_sleeper_rhel.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 180
  delay: 30
  when:
    - yum_update
    - packages_need_update_result_rhel is changed

- name: "Update OS | Update Security and Bugfix Packages"
  ansible.builtin.yum:
    name: '*'
    security: yes
    bugfix: yes
    state: latest
    disablerepo: "{{ disable_repository_list }}"
    enablerepo: "{{ enable_repository_list }}"
    exclude: "{{ exclude_packages_list }}"
  async: 1000
  poll: 0
  register: rhel_yum_update_out
  when:
    - yum_update_security
    - packages_need_update_result_rhel is changed

- name: "YUM - check on async task rhel_yum_update_out"
  ansible.builtin.async_status:
    jid: "{{ rhel_yum_update_out.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 180
  delay: 30
  when:
    - yum_update_security
    - packages_need_update_result_rhel is changed
...
