---
# tasks file for dispatch
- name: "Run os_mgmt.linux_config.{{ __role.role }} role"
  include_role:
    name: "{{ __role.role }}"
    apply:
      tags: "{{ __role.tags }}"
  tags: always
  loop: "{{ linux_config_dispatcher_roles }}"
  loop_control:
    loop_var: __role

...

