---
- hosts: '{{ group_target_os_mgmt | default("all") }}'
  gather_facts: yes
  remote_user: ansible
  roles:
    - role: dispatch
      vars:
        linux_config_dispatcher_roles:
          - {role: motd, var: linux_config_motd, tags: motd}
...
