---
- hosts: motd
  gather_facts: yes
  remote_user: ansible
  roles:
    - role: dispatch
      vars:
        linux_config_dispatcher_roles:
          - {role: motd, var: linux_config_motd, tags: motd}

  #tasks:
    #- name: "Read env Defintions"
    #  include_vars:
    #    file: "{{ item.src }}"
    #  with_filetree: "group_vars/tst/"
    #  when: item.state == 'file'
    #  register: contents

    #- name: Configure Message of today
    #  template:
    #    src: templates/motd-facts.j2
    #    dest: /etc/motd
    #    owner: root
    #    group: root
    #    mode: 0644
    #  become: true

